### ISSUE TITLE
Create an ansible collection for configuring sugarcrm environments

### ISSUE THREAD

**Issue by glevine** [glevine/mac-dev-playbook#2]
Name it `ansible-collection-sugarcrm`. Here are some of the things it should do:

multiverse.yml
```yaml
---
- name: Configure multiverse.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks: []

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

  tasks:
    - import_tasks: tasks/multiverse.yml
      tags: ['multiverse']

    - import_tasks: tasks/ops-terraform-nosilo.yml
      tags: ['ops-terraform-nosilo']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
```

files/multiverse/visual-studio-code-settings.json
```json
{
    "gopls": {
        "formatting.local": "github.com/sugarcrm/multiverse"
    },
    "makefile.configureOnOpen": false,
    "snyk.features.infrastructureAsCode": false
}
```

tasks/multiverse.yml
```yaml
---
- name: Ensure multiverse repository is cloned locally.
  git:
    repo: "{{ multiverse_repo }}"
    dest: "{{ multiverse_repo_local_destination }}"
    accept_hostkey: "{{ multiverse_repo_accept_hostkey }}"
    remote: upstream
    track_submodules: true
  become: false
- name: Install multiverse submodules.
  command: "git -C {{ multiverse_repo_local_destination }} submodule update --init --recursive --remote --rebase"
- name: Add multiverse fork as origin.
  command: TODO
- name: Create multiverse workspace.
  file:
    path: "{{ multiverse_repo_local_destination }}/.vscode"
    state: directory
- name: Install multiverse workspace settings.
  copy:
    src: files/multiverse/visual-studio-code-settings.json
    dest: "{{ multiverse_repo_local_destination }}/.vscode/settings.json"
```

tasks/ops-terraform-nosilo.yml
```yaml
---
- name: Ensure ops-terraform-nosilo repository is cloned locally.
  git:
    repo: "{{ ops_terraform_nosilo_repo }}"
    dest: "{{ ops_terraform_nosilo_repo_local_destination }}"
    accept_hostkey: "{{ ops_terraform_nosilo_repo_accept_hostkey }}"
    remote: upstream
    track_submodules: true
  become: false
```

Use this collection in your playbook.
